name: Deploy

on:
  push:
    branches:
      - main

# Example GitHub Actions workflow using updated versions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Ensure you are using node 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Use the latest v4 version
        with:
          name: production-files
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3 # v3 is fine for download

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Update to v4 if available
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
